### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by prshir** [RDFLib/rdflib-hdt#2]
I try to install the lib on Windows 10 via pip install rdflib-hdt
I have Python 3.7 and new MS Build Tools with C++
While installing an error occured:
    hdt-cpp-1.3.3/libcds/include/libcdsBasics.h(27): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Why did this error happen? And how to solve it? 
I am not an c++ expert so I have no idea why is there no file 'sys/resource.h'

**Comment by Callidon** [comment]
Hi,
I am not that much familiar with building C++ libraries but I am pretty sure that you do have not all necessary C headers files in your system installation. I would recommend to check your C/C++ build installation.
Since it's not an issue related to the library, I'm going to close it.

**Comment by prshir** [comment]
I could install the lib on linux via pip. But then I tried to create whl as pip3.7 wheel . and get the same error
I need whl exactly because I need to install the lib on Windows
Did anybody build whl of this lib? And did anybody used it on Windows? After couple of days of attempts it seems nearly impossible...

**Comment by SRL94** [comment]
Same issue. "sys/resource.h" is a posix header file so VC cannot find it. Have you fixed this issue @prshir ?

**Comment by prshir** [comment]
> Same issue. "sys/resource.h" is a posix header file so VC cannot find it. Have you fixed this issue @prshir ?

No, I didn't fix. As I understood the best way to fix it is to use linux

**Comment by SRL94** [comment]
> > Same issue. "sys/resource.h" is a posix header file so VC cannot find it. Have you fixed this issue @prshir ?
> 
> No, I didn't fix. As I understood the best way to fix it is to use linux

I installed WSL2 on my Win10. This library can be installed and work without any issue on WSL2.
